apiVersion: v1
kind: Service
metadata:
  name: express-eats-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: express-eats-frontend-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
